create table tb_test (
  id                number generated by default on null as identity primary key
 ,file_name         varchar2(400)
 ,file_extension    varchar2(100)
 ,file_content_blob blob
 ,file_content_clob clob);